List soalWord = [
  ['ɝθ', 'Earth'],
  ['kɑf', 'Cough'],
  ['vɪʒən', 'Vision'],
  ['helθ', 'Health'],
  ['fækt', 'Fact'],
  ['vælju', 'Value'],
  ['ɑv', 'Of'],
  ['pʊʃ', 'Push'],
  ['soʊʃəl', 'Social'],
  ['ɑnɪst', 'Honest'],
  ['ɑrkaɪv', 'Archive'],
  ['kæʃ', 'Cache'],
  ['læŋgwɪdʒ', 'language'],
  ['aʊr', 'Hour'],
  ['kætʃ', 'Catch'],
  ['gɪv', 'Give'],
  ['dɪsɪʒən', 'Decision'],
  ['fɪnɪʃ', 'Finish'],
  ['lʌks', 'lux'],
  ['θri', 'three'],
];
