List soalWord = [
  ['ɝθ', 'earth'],
  ['kɑf', 'cough'],
  ['vɪʒən', 'vision'],
  ['helθ', 'health'],
  ['fækt', 'fact'],
  ['vælju', 'value'],
  ['ɑv', 'of'],
  ['pʊʃ', 'push'],
  ['soʊʃəl', 'social'],
  ['ɑnɪst', 'honest'],
  ['ɑrkaɪv', 'archive'],
  ['kæʃ', 'cache'],
  ['læŋgwɪdʒ', 'language'],
  ['aʊr', 'hour'],
  ['kætʃ', 'catch'],
  ['gɪv', 'give'],
  ['dɪsɪʒən', 'decision'],
  ['fɪnɪʃ', 'finish'],
  ['lʌks', 'lux'],
  ['θri', 'three'],
];
