const subBab1 =
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.";
const materi1A =
    "Articulatory phonetics deals with the actual formation of speech sounds, including the specific segmental portion and processes of the production (e.g., organ, place, and manner of articulation), and all similarities and differences between sounds. Sounds in English are produced using the airflow coming out of the lungs and assisted by diaphragm. In the throat, the air passes through the vocal cords. The air will be channeled through the oral cavity or nasal cavity and then processed with the work of the articulation tools in concert to produce a certain sound.";
const materi1B =
    "Here is the description of each part of the picture.\n1.	Nasal Cavity. The nasal sounds are /m/, /n/, and /ŋ/.\n2.	Oral Cavity. The oral sounds are /tʃ/, /ʒ/, and /ð/. Most sounds are produced in oral cavity.\n3.	Alveolar Ridge a small ridge just behind the upper front teeth. For example, /t/, /s/, /d/, /z/, /n/, /l/, and /r/.\n4.	Soft Palate is the soft portion of the roof of the mouth, lying behind the hard palate (i.e., /k/, /g/, /ŋ/).\n5.	Hard Palate is the roof of the mouth just behind the alveolar ridge (i.e., /ʃ/, /tʃ/, /ʒ/, /dʒ/).\n6.	Vocal Cords or Vocal Folds is a fold of tissue in the throat to indicate the vibration when the airstream is allowed to pass between them. It indicates a sound to be voiced or voiceless.";
const materi2 =
    "Sounds fall under two categories, consonants and vowels. The difference between consonants and vowels is basically on the constriction given to the airflow. The consonant sound means a speech sound in which the air stream is at least partially blocked. There are 3 criteria to describe consonants, that are, voicing, place of articulation, and manner of articulation. Voicing deals with the situation of the vocal folds, whether there is a vibration (voiced) or not (voiceless). Place of articulation deals with the position of the constriction of the airflow (i.e., lips, alveolar, palate). Manner of articulation deals with the level or tense of constriction given to the airflow.\n\nGenerally, consonant sounds include all voiceless sounds (e.g., /p/, /s/, /h/), all sounds which the air flows through the mouth by constricting the impeded passage (/l/, trilled /r/, /b/), all sounds which the air flows through nasal cavity (e.g., /m/, /n/), and all sounds that produce an audible friction (e.g., /f/, /v/). The /h/ sound therefore is not classified as vowel because in the articulation process, the vocal folds are open and the sound is generated from the air through the vocal folds without causing vibration. Meanwhile, the vowels are produced with the vocal folds brought closer, so that the air pushes the vocal cords to create friction that produces the sound.\n\nConsonant sounds are divided into voiced and voiceless. This phoneme will be focusing on the American English. The voiced consonants of American English are /b/, /d/, /z/, /l/, /g/, /v/, /ð/, /ʒ/, /ɹ/, /j/, /w/, /n/, /ŋ/ and /m/, and the voiceless consonant are /t/, /k/, /p/, /h/, /f/, /s/, /θ/, and /ʃ/.";
const subConsonantSounds =
    "Consonant sounds can be divided based on the place of articulation.";
const materiConsonantSounds3 =
    "Most phonetician put such a technical name to each sound to simply describe the voicing, place, and manner of its articulation. For example, the technical name of the consonant /ð/ sound is Voiced Dental Fricative. The Voiced indicates that the vocal cords are vibrated when producing the sound. The Dental indicates the tongue that touches the top teeth. While the Fricative indicates that the sound is produced by high pressure airflow going between the tip of the tongue and the top teeth. While for a vowel /ɑ/ sound, the technical name is Open Back Unrounded Vowel. The Open, also known as Low, indicates the tongue position which is far from the roof of the mouth or low in the mouth. The Back also indicates the tongue position which further back. The Unrounded indicates the shape of the lips. Note that all vowels are voiced.";

String image1 = "assets/tabel/image1.svg";
String tabel1 = "assets/tabel/tabel1.svg";
String tabel2 = "assets/tabel/tabel2.svg";
String tabel3 = "assets/tabel/tabel3.svg";
String tabel4 = "assets/tabel/tabel4.svg";
