name: phono
description: Phonetic App Chart.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  expandable: ^4.0.2
  audioplayers: ^0.13.5
  provider: ^3.1.0+1
  flutter_form_builder: ^3.7.2
  
  keyboard_actions: ^3.1.2

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
    - assets/img/phone.png
    - assets/img/ae.png
    - assets/img/book.png
    - assets/img/homework.png
    - assets/img/playbutton.png
    - assets/img/info.png
    - assets/img/exercise.png
    - assets/gif/coba.gif
    - assets/gif/b.gif
    - assets/gif/d.gif
#consonan :
    - assets/audio/b.mp3
    - assets/audio/d.mp3
    # d3 = dʒ
    - assets/audio/d3.mp3
    - assets/audio/f.mp3
    - assets/audio/g.mp3
    - assets/audio/h.mp3
    - assets/audio/j.mp3
    - assets/audio/k.mp3
    - assets/audio/l.mp3
    - assets/audio/m.mp3
    - assets/audio/n.mp3
    - assets/audio/p.mp3
    - assets/audio/r.mp3
    - assets/audio/s.mp3
    - assets/audio/t.mp3
    # tʃ = tf
    - assets/audio/tf.mp3
    - assets/audio/v.mp3
    - assets/audio/w.mp3
    - assets/audio/z.mp3
    #03 = ð
    - assets/audio/03.mp3
    # n2 = ŋ
    - assets/audio/n2.mp3
    # ff = ʃ
    - assets/audio/ff.mp3
    # 3 = ʒ
    - assets/audio/3.mp3
    # 0 = θ
    - assets/audio/0.mp3
    
#vowel :
    # eponi = ë
    - assets/audio/eponi.mp3
    - assets/audio/i.mp3
    - assets/audio/u.mp3
    - assets/audio/a.mp3
    # c2 = ɔ
    - assets/audio/c2.mp3
    # ewalik = ə
    - assets/audio/ewalik.mp3
    #- assets/audio/ə.mp3
    #- assets/audio/ɚ.mp3
    #- assets/audio/ɛ.mp3
    #- assets/audio/ɝ.mp3
    - assets/audio/ɪ.mp3
    - assets/audio/e.mp3
    - assets/audio/3buntut.mp3
    - assets/audio/ebuntut.mp3
    # u2 = ʊ
    - assets/audio/u2.mp3
    # v2 = ʌ
    - assets/audio/v2.mp3

 
  fonts:
    - family: Cabin-Regular
      fonts:
        - asset: assets/fonts/Cabin-Regular.ttf
    - family: Cabin-Medium
      fonts:
        - asset: assets/fonts/Cabin-Medium.ttf
    - family: Cabin-MediumItalic
      fonts:
        - asset: assets/fonts/Cabin-MediumItalic.ttf
    - family: Cabin-SemiBold
      fonts:
        - asset: assets/fonts/Cabin-SemiBold.ttf
    - family: Cabin-Bold
      fonts:
        - asset: assets/fonts/Cabin-Bold.ttf
    - family: Cabin-BoldItalic
      fonts:
        - asset: assets/fonts/Cabin-BoldItalic.ttf