name: phono
description: Phonetic App Chart.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  expandable: ^4.0.2
  audioplayers: ^0.13.5
  provider: ^3.1.0+1
  flutter_form_builder: ^3.7.2
  flutter_svg: ^0.15.0
  
  keyboard_actions: ^3.1.2
  flutter_gifimage: ^1.0.1

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
    - assets/img/phone.png
    - assets/img/wrong.jpg
    - assets/img/tongue.png
    - assets/img/ae.png
    - assets/img/games.svg
    - assets/img/book.png
    - assets/img/homework.png
    - assets/img/playbutton.png
    - assets/img/info.png
    - assets/img/exercise.png
    # TODO: IMAGE MISSPRONON:
    #ɓ 
    #- assets/img/missp/b2.png
    #- assets/img/missp/p.png
    #- assets/img/missp/Rwalik.png
    #t̪
    #- assets/img/missp/t2.png
    #β
    #- assets/img/missp/b3.png
    
    # TODO: GIF CONSONANT: 
    - assets/gif/coba.gif
    - assets/gif/b.gif
    - assets/gif/d.gif
    - assets/gif/consonant/h-min.gif
    - assets/gif/consonant/b-min.gif
    - assets/gif/consonant/d-min.gif
    - assets/gif/consonant/d~-min.gif
    - assets/gif/consonant/d3-min.gif
    - assets/gif/consonant/f-min.gif
    - assets/gif/consonant/g-min.gif
    - assets/gif/consonant/j-min.gif
    - assets/gif/consonant/k-min.gif
    - assets/gif/consonant/l-min.gif
    - assets/gif/consonant/m-min.gif
    - assets/gif/consonant/n-min.gif
    - assets/gif/consonant/o-min.gif
    - assets/gif/consonant/p-min.gif
    - assets/gif/consonant/r-min.gif
    - assets/gif/consonant/s-min.gif
    - assets/gif/consonant/ʃ-min.gif
    - assets/gif/consonant/t-min.gif
    - assets/gif/consonant/tʃ-min.gif
    - assets/gif/consonant/v-min.gif
    - assets/gif/consonant/w-min.gif
    - assets/gif/consonant/z-min.gif
    - assets/gif/consonant/ʒ-min.gif
    - assets/gif/consonant/θ-min.gif
    # TODO: GIF VOWEL:
    - assets/gif/vowel/a-min.gif
    - assets/gif/vowel/æ-min.gif
    - assets/gif/vowel/ə-min.gif
    - assets/gif/vowel/ɛ-min.gif
    - assets/gif/vowel/ɚ-min.gif
    - assets/gif/vowel/ɝ-min.gif
    - assets/gif/vowel/i-min.gif
    - assets/gif/vowel/II-min.gif
    - assets/gif/vowel/ɔ-min.gif
    - assets/gif/vowel/u-min.gif
    - assets/gif/vowel/ʊ-min.gif
    - assets/gif/vowel/ʌ-min.gif 
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    


#consonan :
    - assets/audio/b.mp3
    - assets/audio/d.mp3
    # d3 = dʒ
    - assets/audio/d3.mp3
    - assets/audio/f.mp3
    - assets/audio/g.mp3
    - assets/audio/h.mp3
    - assets/audio/j.mp3
    - assets/audio/k.mp3
    - assets/audio/l.mp3
    - assets/audio/m.mp3
    - assets/audio/n.mp3
    - assets/audio/p.mp3
    - assets/audio/r.mp3
    - assets/audio/s.mp3
    - assets/audio/t.mp3
    # tʃ = tf
    - assets/audio/tf.mp3
    - assets/audio/v.mp3
    - assets/audio/w.mp3
    - assets/audio/z.mp3
    #03 = ð
    - assets/audio/03.mp3
    # n2 = ŋ
    - assets/audio/n2.mp3
    # ff = ʃ
    - assets/audio/ff.mp3
    # 3 = ʒ
    - assets/audio/3.mp3
    # 0 = θ
    - assets/audio/0.mp3
    
#vowel :
    # eponi = ë
    - assets/audio/eponi.mp3
    - assets/audio/i.mp3
    - assets/audio/u.mp3
    - assets/audio/a.mp3
    # c2 = ɔ
    - assets/audio/c2.mp3
    # ewalik = ə
    - assets/audio/ewalik.mp3
    #- assets/audio/ə.mp3
    #- assets/audio/ɚ.mp3
    #- assets/audio/ɛ.mp3
    #- assets/audio/ɝ.mp3
    - assets/audio/ɪ.mp3
    - assets/audio/e.mp3
    - assets/audio/3buntut.mp3
    - assets/audio/ebuntut.mp3
    # u2 = ʊ
    - assets/audio/u2.mp3
    # v2 = ʌ
    - assets/audio/v2.mp3

    # tabel
    - assets/tabel/tabel1.svg
    - assets/tabel/tabel2.svg
    - assets/tabel/tabel3.svg
    - assets/tabel/tabel4.svg
    - assets/tabel/tabel5.svg
    - assets/tabel/image1.svg
    - assets/tabel/image.png

 
  fonts:
    - family: Cabin-Regular
      fonts:
        - asset: assets/fonts/Cabin-Regular.ttf
    - family: Cabin-Medium
      fonts:
        - asset: assets/fonts/Cabin-Medium.ttf
    - family: Cabin-MediumItalic
      fonts:
        - asset: assets/fonts/Cabin-MediumItalic.ttf
    - family: Cabin-SemiBold
      fonts:
        - asset: assets/fonts/Cabin-SemiBold.ttf
    - family: Cabin-Bold
      fonts:
        - asset: assets/fonts/Cabin-Bold.ttf
    - family: Cabin-BoldItalic
      fonts:
        - asset: assets/fonts/Cabin-BoldItalic.ttf