List soalSymbol = [
  ['Resign', 'rɪzaɪn'],
  ['Thought', 'θɑt'],
  ['Wind', 'wɪnd'],
  ['Determine', 'dɪtɝmɪn'],
  ['Recipe', 'resɪpi'],
  ['Phonetic', 'foʊnetɪk'],
  ['Pleasure', 'pleʒɚ'],
  ['Casual', 'kæʒjuəl'],
  ['Beach', 'bitʃ'],
  ['Future', 'fjutʃɚ'],
  ['Through', 'θru'],
  ['Earth', 'ɝθ'],
  ['Tough', 'tʌf'],
  ['Whole', 'hoʊl'],
  ['Either', 'iðɚ'],
  ['Tooth', 'tuθ'],
  ['Enough', 'ɪnʌf'],
  ['Chat', 'tʃæt'],
  ['Verbal', 'vɝbəl'],
  ['Geography', 'dʒiɑgrəfi'],
];
